### ISSUE TITLE
warning when compiling minimal example with "-Werror=free-nonheap-object -O3"

### ISSUE THREAD

**Issue by werto87** [erikerlandson/st_tree#37]
Compiling the following code with  the "-Werror=free-nonheap-object -O3" flags leads to a warning
```c++
#include <st_tree.h>

using namespace st_tree;

int
main ()
{
  tree<int> t;
  t.insert(1);
  return 0;
}
```
**how to reproduce:**
1. create a main.cxx file with the code from above.
2. run "g++ main.cxx -I path/to/st_tree/include -O3 -Werror=free-nonheap-object"

<details><summary>log</summary>

```
In file included from /usr/include/c++/13.2.1/x86_64-pc-linux-gnu/bits/c++allocator.h:33,
                 from /usr/include/c++/13.2.1/bits/allocator.h:46,
                 from /usr/include/c++/13.2.1/string:43,
                 from /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:25,
                 from main.cxx:1:
In member function ‘void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’,
    inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’ at /usr/include/c++/13.2.1/bits/alloc_traits.h:516:23,
    inlined from ‘void st_tree::tree<Data, CSModel, Alloc>::_delete_node(node_type*) [with Data = int; CSModel = st_tree::raw<>; Alloc = std::allocator<int>]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:296:63,
    inlined from ‘st_tree::detail::node_raw<Tree, Data>& st_tree::detail::node_raw<Tree, Data>::operator=(const st_tree::detail::node_raw<Tree, Data>&) [with Tree = st_tree::tree<int>; Data = int]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree_nodes.h:344:48,
    inlined from ‘st_tree::detail::node_raw<Tree, Data>::node_raw(const st_tree::detail::node_raw<Tree, Data>&) [with Tree = st_tree::tree<int>; Data = int]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree_nodes.h:302:15,
    inlined from ‘void std::__new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = st_tree::detail::node_raw<st_tree::tree<int>, int>; _Args = {const st_tree::detail::node_raw<st_tree::tree<int, st_tree::raw<st_tree::arg_unused>, std::allocator<int> >, int>&}; _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’ at /usr/include/c++/13.2.1/bits/new_allocator.h:187:4,
    inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(allocator_type&, _Up*, _Args&& ...) [with _Up = st_tree::detail::node_raw<st_tree::tree<int>, int>; _Args = {const st_tree::detail::node_raw<st_tree::tree<int, st_tree::raw<st_tree::arg_unused>, std::allocator<int> >, int>&}; _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’ at /usr/include/c++/13.2.1/bits/alloc_traits.h:537:17,
    inlined from ‘st_tree::tree<Data, CSModel, Alloc>::node_type* st_tree::tree<Data, CSModel, Alloc>::_new_node() [with Data = int; CSModel = st_tree::raw<>; Alloc = std::allocator<int>]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:290:62,
    inlined from ‘st_tree::detail::node_raw<Tree, Data>::node_type* st_tree::detail::node_raw<Tree, Data>::_copy_data(tree_type&) const [with Tree = st_tree::tree<int>; Data = int]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree_nodes.h:465:39:
/usr/include/c++/13.2.1/bits/new_allocator.h:168:33: error: ‘void operator delete(void*, std::size_t)’ called on unallocated object ‘st_tree::tree<int>::_node_init_val’ [-Werror=free-nonheap-object]
  168 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                 ^
/home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h: In function ‘st_tree::detail::node_raw<Tree, Data>::node_type* st_tree::detail::node_raw<Tree, Data>::_copy_data(tree_type&) const [with Tree = st_tree::tree<int>; Data = int]’:
/home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:310:54: note: declared here
  310 | const typename tree<Data, CSModel, Alloc>::node_type tree<Data, CSModel, Alloc>::_node_init_val;
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
In member function ‘void std::__new_allocator<_Tp>::deallocate(_Tp*, size_type) [with _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’,
    inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::deallocate(allocator_type&, pointer, size_type) [with _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’ at /usr/include/c++/13.2.1/bits/alloc_traits.h:516:23,
    inlined from ‘void st_tree::tree<Data, CSModel, Alloc>::_delete_node(node_type*) [with Data = int; CSModel = st_tree::raw<>; Alloc = std::allocator<int>]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:296:63,
    inlined from ‘st_tree::detail::node_raw<Tree, Data>& st_tree::detail::node_raw<Tree, Data>::operator=(const st_tree::detail::node_raw<Tree, Data>&) [with Tree = st_tree::tree<int>; Data = int]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree_nodes.h:344:48,
    inlined from ‘st_tree::detail::node_raw<Tree, Data>::node_raw(const st_tree::detail::node_raw<Tree, Data>&) [with Tree = st_tree::tree<int>; Data = int]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree_nodes.h:302:15,
    inlined from ‘void std::__new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = st_tree::detail::node_raw<st_tree::tree<int>, int>; _Args = {const st_tree::detail::node_raw<st_tree::tree<int, st_tree::raw<st_tree::arg_unused>, std::allocator<int> >, int>&}; _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’ at /usr/include/c++/13.2.1/bits/new_allocator.h:187:4,
    inlined from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(allocator_type&, _Up*, _Args&& ...) [with _Up = st_tree::detail::node_raw<st_tree::tree<int>, int>; _Args = {const st_tree::detail::node_raw<st_tree::tree<int, st_tree::raw<st_tree::arg_unused>, std::allocator<int> >, int>&}; _Tp = st_tree::detail::node_raw<st_tree::tree<int>, int>]’ at /usr/include/c++/13.2.1/bits/alloc_traits.h:537:17,
    inlined from ‘st_tree::tree<Data, CSModel, Alloc>::node_type* st_tree::tree<Data, CSModel, Alloc>::_new_node() [with Data = int; CSModel = st_tree::raw<>; Alloc = std::allocator<int>]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:290:62,
    inlined from ‘void st_tree::tree<Data, CSModel, Alloc>::emplace(Args&& ...) [with Args = {const int&}; Data = int; CSModel = st_tree::raw<>; Alloc = std::allocator<int>]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:194:26,
    inlined from ‘void st_tree::tree<Data, CSModel, Alloc>::insert(const data_type&) [with Data = int; CSModel = st_tree::raw<>; Alloc = std::allocator<int>]’ at /home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:200:49,
    inlined from ‘int main()’ at main.cxx:9:11:
/usr/include/c++/13.2.1/bits/new_allocator.h:168:33: error: ‘void operator delete(void*, std::size_t)’ called on unallocated object ‘st_tree::tree<int>::_node_init_val’ [-Werror=free-nonheap-object]
  168 |         _GLIBCXX_OPERATOR_DELETE(_GLIBCXX_SIZED_DEALLOC(__p, __n));
      |                                 ^
/home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h: In function ‘int main()’:
/home/walde/.conan2/p/st_trdd8863f0b6958/p/include/st_tree.h:310:54: note: declared here
  310 | const typename tree<Data, CSModel, Alloc>::node_type tree<Data, CSModel, Alloc>::_node_init_val;
      |                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```

</details>

**Comment by turtle-dragonfly** [comment]
I have encountered this as well — GCC 12.2.0, in my case.

It could very well be a false-positive. GCC has had several related to this warning, recently. See meta-bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=99098

Also, in my case it compiles fine with clang (14.0.6), which is a slight mark in favor of the false positive idea — clang supports the same warning, but it is not triggered, here.

**Comment by turtle-dragonfly** [comment]
And, in case it's not obvious, this can be worked around with a compiler-specific disable of the warning.

Towards the end of  `node_raw& node_raw::operator=(...)`:
```
#if defined(__GNUC__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wfree-nonheap-object"
#endif
        if (ancestor) this->tree()._delete_node(r);
#if defined(__GNUC__)
#pragma GCC diagnostic pop
#endif
```

**Comment by erikerlandson** [comment]
Back in the day, I ran the entire test suite against valgrind, and it was clean.  My best guess is that it's a false positive but I'll take a look at it. It's pushing 10 years since I've actually done any regular programming in c++, so it's getting increasingly hard for me to maintain this project 😂

**Comment by erikerlandson** [comment]
I was able to reproduce this warning in the unit testing build, and fixed it using the `#pragma` guard from @turtle-dragonfly above.  I published a new release `version_1.3.0`  with this fix.

I also added a new `make memtest` target that will run the unit tests with valgrind (if cmake finds valgrind in your path).

I validated that valgrind will detect free-nonheap-mem errors, and it's not detecting any errors on either unit tests or examples, so I am reasonably confident that this is a false positive.
